# Generated by Django 3.1.4 on 2021-01-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='image',
            field=models.FileField(upload_to='Device'),
        ),
    ]
