# Generated by Django 3.1.4 on 2021-02-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_visit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
