# Generated by Django 3.1.4 on 2021-02-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210213_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_visit',
        ),
    ]
