# Generated by Django 3.1.4 on 2021-03-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_last_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_contributor',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_translator',
        ),
    ]
