# Generated by Django 3.1.4 on 2021-04-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210316_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='country',
        ),
        migrations.AddField(
            model_name='customuser',
            name='language_choice',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German')], default='en', max_length=2),
        ),
    ]
