# Generated by Django 3.1.4 on 2021-04-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210403_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language_choice',
            field=models.CharField(choices=[('en-us', 'English-US'), ('en-gb', 'English-GB'), ('de-de', 'German')], default='en-us', max_length=5),
        ),
    ]
