# Generated by Django 3.1.4 on 2021-02-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('connector', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='Device')),
                ('release_date', models.DateField()),
                ('manufacturer', models.CharField(max_length=200)),
                ('generation', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('SL', 'SMART_LIGHTING'), ('SLO', 'SMART_LOCK'), ('SMW', 'SMART_METERING_WATER'), ('SME', 'SMART_METERING_ELECTRICITY'), ('SMWA', 'SMAERT_METERING_WARMTH'), ('VA', 'VIRTUAL_ASSISTANT'), ('ST', 'SMART_THERMOSTAT'), ('SC', 'SMART_CAM'), ('SSS', 'SMART_SECURITY_SYSTEM')], max_length=4)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Device',
            },
        ),
        migrations.CreateModel(
            name='DeviceEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('firmware_id', models.AutoField(primary_key=True, serialize=False)),
                ('version_number', models.CharField(max_length=50, verbose_name='Versionnumber')),
                ('changelog', models.CharField(max_length=500, verbose_name='Changelog')),
                ('changelog_en', models.CharField(max_length=500, null=True, verbose_name='Changelog')),
                ('changelog_de', models.CharField(max_length=500, null=True, verbose_name='Changelog')),
                ('release_date', models.DateField(verbose_name='Release Date')),
            ],
            options={
                'verbose_name': 'Firmware',
                'verbose_name_plural': 'Firmwares',
            },
        ),
        migrations.CreateModel(
            name='PrivacyIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discovery', models.DateField(max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('paper_url', models.URLField(max_length=500, verbose_name='URL to the Article to the Privacy Issue')),
                ('patch_date', models.DateField(blank=True, null=True, verbose_name='Privacy Issue got resolved/updated on:')),
                ('url_patch', models.URLField(blank=True, max_length=500, verbose_name='URL to the Privacy Issue update')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discovery', models.DateField(verbose_name='Vulnerability was found on:')),
                ('description', models.CharField(max_length=500, verbose_name='Description of the Vulnerability ')),
                ('paper_url', models.URLField(max_length=500, verbose_name='URL to the Article to the Vulnerability')),
                ('patch_date', models.DateField(blank=True, null=True, verbose_name='Vulnerability was patched on:')),
                ('url_patch', models.URLField(blank=True, max_length=500, verbose_name='URL to the Patch Article')),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('modified', models.DateTimeField(blank=True, editable=False, null=True)),
                ('category', models.CharField(choices=[('Firmware', 'Firmware'), ('Physical', 'Physical'), ('Others', 'Others')], max_length=8)),
                ('device_id', models.ManyToManyField(to='smarthome.Device', verbose_name='Vulnerability exploitable by:')),
            ],
            options={
                'verbose_name': 'Vulnerability',
                'verbose_name_plural': 'Vulnerabilities',
            },
        ),
    ]
