# Generated by Django 3.1.4 on 2021-03-16 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector', models.CharField(max_length=30)),
                ('connector_en', models.CharField(max_length=30, null=True)),
                ('connector_de', models.CharField(max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Connector',
                'verbose_name_plural': 'Connectors',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='Device')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('manufacturer', models.CharField(max_length=200)),
                ('generation', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('Smart_Lightning', 'Smart_Lightning'), ('Smart_Lock', 'Smart_Lock'), ('Virtual_Assistant', 'Virtual_Assistant')], max_length=20)),
                ('compatible_device', models.ManyToManyField(blank=True, related_name='_device_compatible_device_+', to='smarthome.Device', verbose_name='Compatible with')),
                ('connector', models.ManyToManyField(blank=True, to='smarthome.Connector')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('standard', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Standard',
                'verbose_name_plural': 'Standard',
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discovery', models.DateField(verbose_name='Vulnerability was found on:')),
                ('description', models.CharField(max_length=500, verbose_name='Description of the Vulnerability ')),
                ('description_en', models.CharField(max_length=500, null=True, verbose_name='Description of the Vulnerability ')),
                ('description_de', models.CharField(max_length=500, null=True, verbose_name='Description of the Vulnerability ')),
                ('paper_url', models.URLField(max_length=500, verbose_name='URL to the Article to the Vulnerability')),
                ('patch_date', models.DateField(blank=True, null=True, verbose_name='Vulnerability was patched on:')),
                ('url_patch', models.URLField(blank=True, max_length=500, verbose_name='URL to the Patch Article')),
                ('category', models.CharField(choices=[('Firmware', 'Firmware'), ('Physical', 'Physical'), ('Others', 'Others')], max_length=8)),
                ('device_id', models.ManyToManyField(to='smarthome.Device', verbose_name='Vulnerability exploitable by:')),
            ],
            options={
                'verbose_name': 'Vulnerability',
                'verbose_name_plural': 'Vulnerabilities',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('description_en', models.CharField(max_length=300, null=True)),
                ('description_de', models.CharField(max_length=300, null=True)),
                ('paper_url', models.URLField(max_length=500, verbose_name='URL to the Article to the Privacy Concern')),
                ('device_id', models.ManyToManyField(to='smarthome.Device', verbose_name='Privacy Concern affects the following devices:')),
            ],
        ),
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('firmware_id', models.AutoField(primary_key=True, serialize=False)),
                ('version_number', models.CharField(max_length=50, verbose_name='Versionnumber')),
                ('changelog', models.CharField(max_length=500, verbose_name='Changelog')),
                ('changelog_en', models.CharField(max_length=500, null=True, verbose_name='Changelog')),
                ('changelog_de', models.CharField(max_length=500, null=True, verbose_name='Changelog')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release Date')),
                ('compatibility_list', models.ManyToManyField(to='smarthome.Device', verbose_name='Firmware Compatible with')),
            ],
            options={
                'verbose_name': 'Firmware',
                'verbose_name_plural': 'Firmwares',
            },
        ),
        migrations.CreateModel(
            name='DeviceEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarthome.connector')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarthome.device')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarthome.room')),
            ],
            options={
                'verbose_name': 'Device Entry',
                'verbose_name_plural': 'Device Entries',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='standard',
            field=models.ManyToManyField(blank=True, to='smarthome.Standard'),
        ),
        migrations.AddConstraint(
            model_name='connector',
            constraint=models.UniqueConstraint(fields=('connector',), name='unique_connector'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='room'),
        ),
        migrations.AddConstraint(
            model_name='deviceentry',
            constraint=models.UniqueConstraint(fields=('room', 'device', 'connector', 'quantity'), name='unique_entry'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('name', 'manufacturer', 'generation'), name='unique_device'),
        ),
    ]
