# Generated by Django 3.1.4 on 2021-03-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='release_date',
        ),
        migrations.AlterField(
            model_name='device',
            name='connector',
            field=models.ManyToManyField(to='smarthome.Connector'),
        ),
    ]
