# Generated by Django 3.1.4 on 2021-02-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FundamentalsEntry',
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='deviceentry',
            options={'verbose_name': 'Device Entry', 'verbose_name_plural': 'Device Entries'},
        ),
    ]
