# Generated by Django 3.1.4 on 2021-07-22 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smarthome', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='firmware',
            name='compatibility_list',
            field=models.ManyToManyField(to='smarthome.Device', verbose_name='Firmware Compatible with'),
        ),
        migrations.AddField(
            model_name='deviceentry',
            name='connector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarthome.connector'),
        ),
        migrations.AddField(
            model_name='deviceentry',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarthome.device'),
        ),
        migrations.AddField(
            model_name='deviceentry',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarthome.room'),
        ),
        migrations.AddField(
            model_name='device',
            name='compatible_device',
            field=models.ManyToManyField(blank=True, related_name='_device_compatible_device_+', to='smarthome.Device', verbose_name='Compatible with'),
        ),
        migrations.AddField(
            model_name='device',
            name='connector',
            field=models.ManyToManyField(to='smarthome.Connector'),
        ),
        migrations.AddField(
            model_name='device',
            name='standard',
            field=models.ManyToManyField(blank=True, to='smarthome.Standard'),
        ),
        migrations.AddField(
            model_name='dataprotectioninformation',
            name='device_id',
            field=models.ManyToManyField(to='smarthome.Device', verbose_name='Privacy Concern affects the following devices:'),
        ),
        migrations.AddConstraint(
            model_name='connector',
            constraint=models.UniqueConstraint(fields=('connector',), name='unique_connector'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='room'),
        ),
        migrations.AddConstraint(
            model_name='deviceentry',
            constraint=models.UniqueConstraint(fields=('room', 'device', 'connector', 'quantity'), name='unique_entry'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('name', 'manufacturer', 'generation'), name='unique_device'),
        ),
    ]
