# Generated by Django 3.1.4 on 2021-01-29 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smarthome', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interface',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarthome.device'),
        ),
        migrations.AddField(
            model_name='firmware',
            name='compatibility_list',
            field=models.ManyToManyField(to='smarthome.Device', verbose_name='Firmware Kompatibel mit'),
        ),
        migrations.AddField(
            model_name='deviceentry',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarthome.device'),
        ),
        migrations.AddField(
            model_name='deviceentry',
            name='unique_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarthome.room'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('name', 'manufacturer_name', 'generation'), name='unique_device'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('user', 'room_name'), name='unique_room'),
        ),
        migrations.AddConstraint(
            model_name='deviceentry',
            constraint=models.UniqueConstraint(fields=('unique_room', 'device', 'quantity'), name='unique_entry'),
        ),
    ]
