# Generated by Django 3.1.4 on 2021-02-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Device', 'verbose_name_plural': 'Device'},
        ),
        migrations.AlterModelOptions(
            name='vulnerability',
            options={'verbose_name': 'Vulnerability', 'verbose_name_plural': 'Vulnerabilities'},
        ),
        migrations.AlterField(
            model_name='firmware',
            name='changelog',
            field=models.CharField(max_length=500, verbose_name='Changelog'),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='changelog_de',
            field=models.CharField(max_length=500, null=True, verbose_name='Changelog'),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='changelog_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Changelog'),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='compatibility_list',
            field=models.ManyToManyField(to='smarthome.Device', verbose_name='Firmware Compatible with'),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='release_date',
            field=models.DateField(verbose_name='Release Date'),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='version_number',
            field=models.CharField(max_length=50, verbose_name='Versionnumber'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='category',
            field=models.CharField(max_length=20, verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='description',
            field=models.CharField(max_length=300, verbose_name='Description of the Vulnerability '),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='device_id',
            field=models.ManyToManyField(to='smarthome.Device', verbose_name='Vulnerability useable by Device:'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='discovered_date',
            field=models.DateField(verbose_name='Vulnerability was found on:'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='patch_date',
            field=models.DateField(verbose_name='Vulnerability was patched on:'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='patched',
            field=models.BooleanField(default=False, verbose_name='Vulnerability patched:'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='url',
            field=models.URLField(verbose_name='URL to the Article to the Vulnerability'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='url_patch',
            field=models.URLField(verbose_name='Link to the Patch Article'),
        ),
    ]
