# Generated by Django 3.1.4 on 2021-04-05 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataprotectioninformation',
            options={'verbose_name': 'Data Protection Information', 'verbose_name_plural': 'Data Protection Information'},
        ),
    ]
