# Generated by Django 3.1.4 on 2021-02-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0002_auto_20210208_2143'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deviceentry',
            name='unique_entry',
        ),
        migrations.AddConstraint(
            model_name='deviceentry',
            constraint=models.UniqueConstraint(fields=('unique_room', 'device', 'connector', 'quantity'), name='unique_entry'),
        ),
    ]
