# Generated by Django 3.1.4 on 2021-02-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0002_auto_20210210_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='modified',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='patch_date',
            field=models.DateField(blank=True, null=True, verbose_name='Vulnerability was patched on:'),
        ),
    ]
