# Generated by Django 3.1.4 on 2021-02-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0002_auto_20210211_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
